export const SERVICE_COPY: Record<string, { title: string; description: string }> = {
  standard: {
    title: 'Standard Cleaning',
    description: 'Regular upkeep for a consistently fresh, tidy home.',
  },
  deep: {
    title: 'Deep Cleaning',
    description: 'A thorough reset for first visits, seasonal refreshes, or after a long break.',
  },
  move: {
    title: 'Move-In / Move-Out',
    description: 'Full detail for empty homes before keys change hands.',
  },
  laundry: {
    title: 'Cleaning + Laundry',
    description: 'Full home clean plus wash, dry, and fold for busy households.',
  },
}

export const t = {
  nav: {
    services: 'Services',
    prices: 'Packages',
    areas: 'Areas',
    about: 'About',
    faq: 'FAQ',
    cta: 'Book Now',
    openMenu: 'Open menu',
    closeMenu: 'Close',
    mobileNav: 'Mobile navigation',
  },
  hero: {
    badge: 'Trusted across New Jersey',
    lines: [
      'Premium home',
      'cleaning that',
      'actually glows',
    ],
    accent: 'glows',
    subtitle: 'Professional residential cleaning across Monmouth, Ocean, Mercer & Burlington Counties. Book online in minutes.',
    pillars: ['Standard', 'Deep Clean', 'Move-In/Out'] as [string, string, string],
    cardLabel: 'Free quote',
    cardTitle: 'Book your clean',
    cardSub: 'Pick a service, enter your ZIP\nand we\'ll confirm your slot',
    ctaSecondary: 'View services',
  },
  marquee: {
    items: [
      'Standard Cleaning',
      'Deep Clean',
      'Move-In / Move-Out',
      'Laundry + Fold',
      'Weekly Plans',
      'Eco-Friendly Products',
      'NJ Local Crew',
      'Free Quotes',
      'Same-Week Booking',
      'Insured & Vetted',
    ] as const,
  },
  trust: {
    items: [
      { value: '118+', label: 'Cities served' },
      { value: '4', label: 'Service types' },
      { value: '100%', label: 'Satisfaction focus' },
      { value: 'Same-week', label: 'Scheduling' },
    ] as const,
  },
  about: {
    eyebrow: 'About us',
    titleBefore: 'Cleaning with a ',
    titleEm: 'royal glow',
    paragraphs: [
      'Royal Glow Cleaning turns everyday housekeeping into something you actually look forward to — a home that feels bright, fresh, and genuinely cared for.',
      'We serve families across the Jersey Shore and Central NJ with punctual crews, transparent pricing, and attention to the details that matter.',
      'New client? Start with a deep clean, then switch to recurring service to keep that just-cleaned feeling all year.',
    ],
    teamImageAlt: 'Royal Glow professional cleaning team',
    ctaTitle: 'Ready for a home that shines?',
    ctaText: 'Request a visit — we\'ll confirm your ZIP and send a clear quote with no surprises.',
    ctaBtn: 'Get a free quote',
    ctaNote: 'Free quote · No commitment · Same-week availability',
    ctaImageAlt: 'Bright clean interior after Royal Glow service',
  },
  services: {
    eyebrow: 'What we offer',
    titleBefore: 'Our ',
    titleEm: 'services',
    lead: 'Choose the clean that fits your home. Tap Details for the full checklist and pricing.',
    book: 'Book now',
    details: 'Details',
    prev: 'Previous',
    next: 'Next',
    notes: 'Final pricing depends on home size, condition, and any add-ons you request.',
  },
  howItWorks: {
    eyebrow: 'Simple process',
    titleBefore: 'How it ',
    titleEm: 'works',
    lead: 'From first message to a spotless home — three easy steps.',
    steps: [
      { title: 'Tell us about your home', text: 'Share your ZIP, home size, and the service you need. We\'ll confirm availability and pricing.' },
      { title: 'We match your schedule', text: 'Pick a time that works. Our team arrives on time with supplies and a clear plan for your space.' },
      { title: 'Enjoy the glow', text: 'Walk into a fresh, detailed home. Rebook recurring cleans or add extras anytime.' },
    ] as const,
  },
  whyUs: {
    eyebrow: 'Why Royal Glow',
    titleBefore: 'The ',
    titleEm: 'difference',
    lead: 'More than a quick wipe-down — a reliable partner for a cleaner home.',
    items: [
      { title: 'Vetted professionals', text: 'Experienced, respectful crews who treat your home like their own.' },
      { title: 'Transparent pricing', text: 'Clear rates by bedroom count. No hidden fees — you know before we arrive.' },
      { title: 'Eco-conscious products', text: 'Effective, family-friendly products safe for kids and pets.' },
      { title: 'Flexible scheduling', text: 'Weekly, biweekly, monthly, or one-time — built around your calendar.' },
      { title: 'Detail-driven', text: 'Baseboards, fixtures, and corners included in deep and move-out cleans.' },
      { title: 'Local & responsive', text: 'NJ-based team with fast replies by phone, email, or WhatsApp.' },
    ] as const,
  },
  prices: {
    eyebrow: 'How it works',
    titleBefore: 'Pick your ',
    titleEm: 'clean',
    lead: 'Choose the package that fits your home. Final pricing depends on size, condition, and scope — we confirm a clear quote before we start.',
    book: 'Get a quote',
    quoteBadge: 'Custom quote',
    note: 'Tell us your home size and what you need. We\'ll estimate the work and send an exact price — no surprises.',
    plans: [
      {
        id: 'standard',
        title: 'Standard Cleaning',
        text: 'Regular upkeep to keep everyday spaces fresh and tidy.',
        highlights: [
          'Dusting, vacuum & mop',
          'Kitchen & bathrooms',
          'Ideal for weekly or biweekly',
        ],
      },
      {
        id: 'deep',
        title: 'Deep Cleaning',
        text: 'A thorough reset for first visits, seasons, or after a long break.',
        highlights: [
          'Everything in standard',
          'Baseboards, grout & detail',
          'Best first-time baseline',
        ],
        featured: true,
      },
      {
        id: 'move',
        title: 'Move-In / Move-Out',
        text: 'Empty-home detail so keys change hands with confidence.',
        highlights: [
          'Cabinets, fridge & oven',
          'Closets, shelves & floors',
          'Final walkthrough check',
        ],
      },
    ] as const,
  },
  areas: {
    eyebrow: 'Coverage',
    titleBefore: 'Service ',
    titleEm: 'area',
    lead: 'We clean homes across Monmouth, Ocean, Mercer & Burlington Counties. Not sure if we cover yours?',
    tabsLabel: 'Counties we serve',
    zipLabel: 'Check your ZIP',
    zipPh: '07701',
    zipOk: 'Great news — we service your area!',
    zipBad: 'Sorry, this ZIP isn\'t in our service area yet.',
    zipInvalid: 'Enter a valid 5-digit US ZIP',
    zipHint: 'Questions? Call us at',
  },
  reviews: {
    eyebrow: 'Testimonials',
    titleBefore: 'Happy ',
    titleEm: 'homes',
    lead: 'What local families say after working with Royal Glow.',
  },
  faq: {
    eyebrow: 'FAQ',
    titleBefore: 'Common ',
    titleEm: 'questions',
    lead: 'Quick answers before you book.',
    items: [
      { q: 'Do I need to be home during the clean?', a: 'Not necessarily. Many clients provide entry instructions. We\'ll coordinate access details when we confirm your appointment.' },
      { q: 'Do you bring supplies and equipment?', a: 'Yes — our team arrives with professional-grade products and tools. If you prefer specific products, let us know in advance.' },
      { q: 'How long does a standard clean take?', a: 'Typically 2–4 hours depending on home size and condition. Deep and move-out cleans may take longer.' },
      { q: 'What\'s the difference between standard and deep cleaning?', a: 'Standard covers regular upkeep. Deep cleaning adds detail work like baseboards, grout, appliance exteriors, and hard-to-reach spots.' },
      { q: 'Can I book recurring service?', a: 'Absolutely. Weekly, biweekly, and monthly plans are available. We recommend starting with a deep clean for best results.' },
      { q: 'How do you price laundry with cleaning?', a: 'Share how many loads and your home size when you request a quote — we\'ll include laundry in your custom estimate.' },
    ] as const,
  },
  ctaBanner: {
    title: 'Your clean home is one click away',
    text: 'Get a free quote for your ZIP — most requests answered within a few hours.',
    btn: 'Book your clean',
    phone: 'Or call us',
    trust: ['Free quote', 'Insured crew', 'Same-week slots'] as const,
  },
  serviceModal: {
    includes: 'What\'s included',
    quote: 'Custom quote',
    quoteText: 'Final pricing depends on home size, condition, and the amount of work. We confirm a clear quote before we start.',
    book: 'Get a quote',
    close: 'Close',
  },
  contact: {
    eyebrow: 'Get started',
    heading: 'Book your',
    headingEm: 'visit',
    lead: 'Choose a service, leave your details and ZIP — we\'ll reach out to confirm.',
    visualLabel: 'Royal Glow Cleaning',
    visualText: 'Professional home cleaning · New Jersey',
    visualAlt: 'Bright clean home interior',
    formTitle: 'Request a quote',
    name: 'Full name',
    namePh: 'Your name',
    phone: 'Phone',
    phonePh: '(908) 733-6768',
    email: 'Email',
    emailPh: 'you@email.com',
    zip: 'ZIP code',
    zipPh: '07701',
    service: 'Service type',
    servicePh: 'Select a service',
    comment: 'Notes',
    commentPh: 'Home size, pets, preferred day…',
    consent: 'By submitting, you agree to the processing of your personal data',
    submit: 'Send request',
    submitting: 'Sending…',
    successTitle: 'Thank you!',
    successText: 'We\'ll reach out shortly to confirm availability in your ZIP.',
    zipError: 'This ZIP is outside our service area',
    zipFormatError: 'Enter a valid 5-digit US ZIP',
    submitError: 'Something went wrong. Please try again or call us directly.',
  },
  booking: {
    modalTitle: 'Quick booking',
    namePh: 'your name',
    phonePh: 'phone number',
    emailPh: 'email (optional)',
    submit: 'Send request',
    submitting: 'Sending…',
    consent: 'By submitting, you agree to the processing of your personal data',
    successTitle: 'Request received!',
    successText: 'We\'ll call or message you shortly.',
    close: 'Close',
    error: 'Please check your phone number and try again',
    submitError: 'Could not send your request. Please try again or message us on WhatsApp.',
    or: 'or',
    socialLead: 'Message us on',
    whatsapp: 'WhatsApp',
    promptTitle: 'Need a clean home?',
    promptText: 'Leave a request — we\'ll find a time that works in your area.',
    promptBtn: 'Book now',
  },
  footer: {
    navLabel: 'Navigation',
    links: ['About', 'Services', 'Packages', 'Areas', 'FAQ'] as [string, string, string, string, string],
    linkTargets: ['#about', '#services', '#prices', '#areas', '#faq'] as const,
    hours: 'Operating hours',
    hoursWeek: 'Mon–Fri: 8 am – 8 pm',
    hoursWeekend: 'Sat–Sun: 8 am – 6 pm',
    policiesTitle: 'Policies',
    legal: [
      { label: 'Privacy Policy', href: '/privacy-policy' },
      { label: 'Terms & Conditions', href: '/terms-and-conditions' },
      { label: 'Cancellation Policy', href: '/cancellation-policy' },
      { label: 'Cookies Policy', href: '/cookies-policy' },
      { label: 'Subscription Terms', href: '/subscription-terms' },
    ] as const,
    contactsTitle: 'Contact',
    social: 'Connect',
    rights: 'All rights reserved.',
    craftedBy: 'Website by',
    craftedByName: 'TeleBots',
    craftedByUrl: 'https://telebots.site/en',
  },
} as const

export function getServiceOptions() {
  return Object.entries(SERVICE_COPY).map(([id, copy]) => ({ id, title: copy.title }))
}

export function getServiceTitle(id: string) {
  return SERVICE_COPY[id]?.title ?? id
}
